[build]
cmd = "go build -o /app/tmp/main ./main.go"
bin = "/app/tmp/main"
full_bin = "/app/tmp/main"
include_ext = ["go"]
exclude_dir = ["vendor", "tmp"]
delay = 500
kill_signal = "SIGKILL"
poll = true                  # ✅ Activation du polling pour Docker
poll_interval = 1000         # ✅ 1000ms = 1s entre les vérifications