# ---- Build Stage ----
FROM golang:1.24 AS builder

# Définir le répertoire de travail
WORKDIR /app

# Activer le proxy Go pour éviter des problèmes de téléchargement
ENV GOPROXY=https://proxy.golang.org,direct

# Copier et télécharger les dépendances
COPY go.mod go.sum ./
RUN go mod download

# Copier le reste des fichiers
COPY . .

# Compiler l'application avec une version statique de glibc
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o api ./*.go

# ---- Final Stage ----
FROM alpine:latest

# Définir le répertoire de travail
WORKDIR /app

# Copier le binaire Go compilé depuis l’étape précédente
COPY --from=builder /app/api /app/api

# Exposer le port
EXPOSE 8080

# Démarrer l’application
CMD ["/app/api"]
